server:
  port: 8088

# LOGGING
logging:
  level: debug

# DATA REST (RepositoryRestProperties)
spring:
  data:
    rest:
      base-path: /api
#    mongodb:
#      uri: mongodb://simon:123456@192.168.150.128:27017/MongoDemo
