server:
  port: 8088

# LOGGING
logging:
  level: debug

# DATA REST (RepositoryRestProperties)
spring:
  data:
    rest:
      base-path: /api
#    mongodb:
#      uri: mongodb://root:root@127.0.0.1:27017/db_spring5
